INSERT INTO ENDERECO_EMPRESA
    (BAIRRO, CIDADE, COMPLEMENTO, ENDERECO, ESTADO, NUMERO_CASA)
VALUES
    ('Moji das cruzes', 'São Paulo', 'Edificio Copa','Av. Rua dos valdos', 'São Paulo', '405'),
    ('Moji das cruzes', 'São Paulo', 'Edificio Copa','Av. Rua dos valdos', 'São Paulo', '405'),
    ('Moji das cruzes', 'São Paulo', 'Edificio Copa','Av. Rua dos valdos', 'São Paulo', '405'),
    ('Moji das cruzes', 'São Paulo', 'Edificio Copa','Av. Rua dos valdos', 'São Paulo', '405'),
    ('Moji das cruzes', 'São Paulo', 'Edificio Copa','Av. Rua dos valdos', 'São Paulo', '405'),
    ('Moji das cruzes', 'São Paulo', 'Edificio Copa','Av. Rua dos valdos', 'São Paulo', '405'),
    ('Moji das cruzes', 'São Paulo', 'Edificio Copa','Av. Rua dos valdos', 'São Paulo', '405'),
    ('Moji das cruzes', 'São Paulo', 'Edificio Copa','Av. Rua dos valdos', 'São Paulo', '405'),
    ('Moji das cruzes', 'São Paulo', 'Edificio Copa','Av. Rua dos valdos', 'São Paulo', '405');